// The OpenNext worker is generated by `opennextjs-cloudflare build`.
// @ts-expect-error Generated only after the Cloudflare build step.
import openNextHandler from "./.open-next/worker.js";
// @ts-expect-error Generated only after the secret-safe Worker build gate passes.
import { SAFE_WORKER_BUILD_ATTESTATION } from "./.open-next/safe-build-attestation.mjs";

import { runV2ScheduledJobs } from "./src/lib/v2/infrastructure/cloudflare/scheduled-jobs";

type WorkerEnv = Cloudflare.Env & {
  CRON_SECRET?: string;
};

type OpenNextWorkerHandler = {
  fetch(request: Request, env: WorkerEnv, context: ExecutionContext): Promise<Response>;
};

const handler = openNextHandler as OpenNextWorkerHandler;

if (SAFE_WORKER_BUILD_ATTESTATION !== "light-house-worker-safe-v1") {
  throw new Error("The Worker artifact did not pass the Light-House safe-build gate.");
}

const worker = {
  fetch: handler.fetch,
  async scheduled(
    controller: ScheduledController,
    env: WorkerEnv,
    context: ExecutionContext,
  ) {
    await runV2ScheduledJobs({
      cron: controller.cron,
      cronSecret: env.CRON_SECRET,
      dispatch: (request) => handler.fetch(request, env, context),
    });
  },
};

export default worker;
