import type { PropertyDefinition, PropertyGroupDefinition, PropertyOption } from "./types";

export const ASSET_CATEGORY_OPTIONS: PropertyOption[] = [
  { value: "gear", label: "장비" },
  { value: "collection", label: "수집품" },
];

export const ASSET_CONDITION_OPTIONS: PropertyOption[] = [
  { value: "mint", label: "최상" },
  { value: "good", label: "양호" },
  { value: "fair", label: "보통" },
  { value: "repair", label: "수리 필요" },
];

export const ASSET_PROPERTY_GROUPS: PropertyGroupDefinition[] = [
  { key: "identity", label: "자산 기본", defaultOpen: true },
  { key: "classification", label: "분류", defaultOpen: true },
  { key: "status", label: "상태", defaultOpen: true },
  { key: "dates", label: "취득 정보", defaultOpen: true },
  { key: "review", label: "메모", defaultOpen: false },
];

export const ASSET_PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  {
    key: "asset.name",
    entityType: "asset",
    field: "name",
    label: "자산명",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["title", "name", "asset", "자산", "자산명", "이름", "물건"],
  },
  {
    key: "asset.brand",
    entityType: "asset",
    field: "brand",
    label: "브랜드",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["brand", "maker", "manufacturer", "브랜드", "제조사"],
  },
  {
    key: "asset.modelName",
    entityType: "asset",
    field: "modelName",
    label: "모델명",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["model", "model name", "모델", "모델명"],
  },
  {
    key: "asset.category",
    entityType: "asset",
    field: "category",
    label: "분류",
    group: "classification",
    valueType: "select",
    display: "segmented",
    options: ASSET_CATEGORY_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["category", "type", "kind", "분류", "유형", "종류"],
  },
  {
    key: "asset.condition",
    entityType: "asset",
    field: "condition",
    label: "현재 상태",
    group: "status",
    valueType: "select",
    display: "select",
    options: ASSET_CONDITION_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["condition", "current condition", "status", "상태", "컨디션"],
  },
  {
    key: "asset.acquiredDate",
    entityType: "asset",
    field: "acquiredDate",
    label: "취득일",
    group: "dates",
    valueType: "date",
    display: "date",
    defaultVisibleInDetail: true,
    sourceAliases: ["acquired", "acquired date", "purchase date", "구입일", "취득일"],
  },
  {
    key: "asset.acquiredPrice",
    entityType: "asset",
    field: "acquiredPrice",
    label: "취득가",
    group: "dates",
    valueType: "number",
    display: "number",
    defaultVisibleInDetail: true,
    sourceAliases: ["price", "cost", "acquired price", "구입가", "취득가", "가격"],
  },
  {
    key: "asset.notes",
    entityType: "asset",
    field: "notes",
    label: "메모",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["notes", "memo", "description", "메모", "설명", "비고"],
  },
];
