import type { PropertyDefinition, PropertyGroupDefinition, PropertyOption } from "./types";

export const CAREER_CATEGORY_OPTIONS: PropertyOption[] = [
  { value: "work", label: "업무" },
  { value: "study", label: "학습" },
  { value: "service", label: "섬김" },
];

export const CAREER_PROPERTY_GROUPS: PropertyGroupDefinition[] = [
  { key: "identity", label: "이력 기본", defaultOpen: true },
  { key: "classification", label: "분류", defaultOpen: true },
  { key: "dates", label: "기간", defaultOpen: true },
  { key: "review", label: "설명", defaultOpen: false },
];

export const CAREER_PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  {
    key: "career.organization",
    entityType: "career",
    field: "organization",
    label: "조직",
    group: "identity",
    valueType: "text",
    display: "text",
    placeholder: "조직명",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["organization", "company", "school", "org", "조직", "회사", "학교"],
  },
  {
    key: "career.role",
    entityType: "career",
    field: "role",
    label: "역할",
    group: "identity",
    valueType: "text",
    display: "text",
    placeholder: "역할/직무",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["role", "title", "position", "job", "역할", "직무", "포지션"],
  },
  {
    key: "career.category",
    entityType: "career",
    field: "category",
    label: "분류",
    group: "classification",
    valueType: "select",
    display: "segmented",
    options: CAREER_CATEGORY_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["category", "type", "분류", "종류", "구분"],
  },
  {
    key: "career.startDate",
    entityType: "career",
    field: "startDate",
    label: "시작일",
    group: "dates",
    valueType: "date",
    display: "date",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["start", "start date", "from", "시작", "시작일"],
  },
  {
    key: "career.endDate",
    entityType: "career",
    field: "endDate",
    label: "종료일",
    group: "dates",
    valueType: "date",
    display: "date",
    allowEmpty: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["end", "end date", "to", "종료", "종료일"],
  },
  {
    key: "career.description",
    entityType: "career",
    field: "description",
    label: "설명",
    group: "review",
    valueType: "longText",
    display: "textarea",
    placeholder: "맡은 일, 배운 점, 주요 성과를 적어둡니다.",
    defaultVisibleInDetail: true,
    sourceAliases: ["description", "highlights", "note", "memo", "설명", "성과", "메모"],
  },
];
