import type { PropertyDefinition, PropertyGroupDefinition, PropertyOption } from "./types";

export const DAILY_MOOD_OPTIONS: PropertyOption[] = [
  { value: "1", label: "1 · 낮음" },
  { value: "2", label: "2 · 무거움" },
  { value: "3", label: "3 · 보통" },
  { value: "4", label: "4 · 좋음" },
  { value: "5", label: "5 · 매우 좋음" },
];

export const DAILY_ENERGY_OPTIONS: PropertyOption[] = [
  { value: "1", label: "낮음" },
  { value: "2", label: "부드러움" },
  { value: "3", label: "안정" },
  { value: "4", label: "집중" },
  { value: "5", label: "고에너지" },
];

export const DAILY_PROPERTY_GROUPS: PropertyGroupDefinition[] = [
  { key: "dates", label: "날짜", defaultOpen: true },
  { key: "status", label: "하루 상태", defaultOpen: true },
  { key: "domain", label: "생활 데이터", defaultOpen: true },
  { key: "classification", label: "감정 태그", defaultOpen: true },
  { key: "review", label: "저널", defaultOpen: false },
];

export const DAILY_PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  {
    key: "daily_log.date",
    entityType: "daily_log",
    field: "date",
    label: "날짜",
    group: "dates",
    valueType: "date",
    display: "date",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["date", "날짜", "일자", "기록일"],
  },
  {
    key: "daily_log.mood",
    entityType: "daily_log",
    field: "mood",
    label: "기분",
    group: "status",
    valueType: "select",
    display: "segmented",
    options: DAILY_MOOD_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["mood", "기분", "감정", "컨디션"],
  },
  {
    key: "daily_log.energy",
    entityType: "daily_log",
    field: "energy",
    label: "에너지",
    group: "status",
    valueType: "select",
    display: "segmented",
    options: DAILY_ENERGY_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["energy", "energy level", "에너지", "활력"],
  },
  {
    key: "daily_log.sleepHours",
    entityType: "daily_log",
    field: "sleepHours",
    label: "수면 시간",
    group: "domain",
    valueType: "number",
    display: "number",
    placeholder: "7.0",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["sleep", "sleep hours", "수면", "수면 시간"],
  },
  {
    key: "daily_log.deepWorkMinutes",
    entityType: "daily_log",
    field: "deepWorkMinutes",
    label: "딥워크",
    group: "domain",
    valueType: "number",
    display: "number",
    placeholder: "120",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["deep work", "focus", "집중", "딥워크", "몰입"],
  },
  {
    key: "daily_log.emotions",
    entityType: "daily_log",
    field: "emotions",
    label: "감정",
    group: "classification",
    valueType: "multiSelect",
    display: "chip",
    placeholder: "감정을 입력하고 Enter",
    defaultVisibleInDetail: true,
    sourceAliases: ["emotion", "emotions", "감정", "감정 태그"],
  },
  {
    key: "daily_log.gratitude",
    entityType: "daily_log",
    field: "gratitude",
    label: "감사",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["gratitude", "thanks", "감사", "감사 기록"],
  },
  {
    key: "daily_log.journal",
    entityType: "daily_log",
    field: "journal",
    label: "일기",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["journal", "diary", "일기", "저널", "본문"],
  },
  {
    key: "daily_log.meditation",
    entityType: "daily_log",
    field: "meditation",
    label: "묵상",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["meditation", "묵상", "quiet time", "qt"],
  },
  {
    key: "daily_log.meditationVerse",
    entityType: "daily_log",
    field: "meditationVerse",
    label: "본문 말씀",
    group: "review",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["verse", "scripture", "본문", "말씀", "구절"],
  },
];
