import type { PropertyDefinition, PropertyGroupDefinition, PropertyOption } from "./types";

export const GIFT_DIRECTION_OPTIONS: PropertyOption[] = [
  { value: "given", label: "준 선물" },
  { value: "received", label: "받은 선물" },
];

export const GIFT_PROPERTY_GROUPS: PropertyGroupDefinition[] = [
  { key: "identity", label: "선물 기본", defaultOpen: true },
  { key: "relations", label: "관계", defaultOpen: true },
  { key: "dates", label: "날짜", defaultOpen: true },
  { key: "review", label: "반응과 메모", defaultOpen: true },
];

export const GIFT_PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  {
    key: "gift.title",
    entityType: "gift",
    field: "title",
    label: "선물명",
    group: "identity",
    valueType: "text",
    display: "text",
    placeholder: "선물 이름",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["title", "name", "gift", "선물", "선물명", "이름"],
  },
  {
    key: "gift.direction",
    entityType: "gift",
    field: "direction",
    label: "방향",
    group: "identity",
    valueType: "select",
    display: "segmented",
    options: GIFT_DIRECTION_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["direction", "type", "kind", "given received", "방향", "구분"],
  },
  {
    key: "gift.personId",
    entityType: "gift",
    field: "personId",
    label: "대상 인물",
    group: "relations",
    valueType: "relation",
    display: "select",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["person", "person id", "recipient", "giver", "대상", "사람", "인물"],
  },
  {
    key: "gift.occurredAt",
    entityType: "gift",
    field: "occurredAt",
    label: "선물일",
    group: "dates",
    valueType: "date",
    display: "date",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["date", "occurred", "occurred at", "gift date", "날짜", "선물일"],
  },
  {
    key: "gift.satisfaction",
    entityType: "gift",
    field: "satisfaction",
    label: "반응",
    group: "review",
    valueType: "text",
    display: "text",
    placeholder: "만족도 / 반응",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["satisfaction", "reaction", "response", "반응", "만족도"],
  },
  {
    key: "gift.notes",
    entityType: "gift",
    field: "notes",
    label: "메모",
    group: "review",
    valueType: "longText",
    display: "textarea",
    placeholder: "선물의 맥락이나 다음 참고사항",
    defaultVisibleInDetail: true,
    sourceAliases: ["notes", "memo", "description", "메모", "비고"],
  },
];
