import type { PropertyDefinition, PropertyGroupDefinition } from "./types";

export const HABIT_PROPERTY_GROUPS: PropertyGroupDefinition[] = [
  { key: "identity", label: "습관 기본", defaultOpen: true },
  { key: "status", label: "상태", defaultOpen: true },
  { key: "domain", label: "반복 규칙", defaultOpen: true },
  { key: "review", label: "설명", defaultOpen: false },
];

export const HABIT_PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  {
    key: "habit.title",
    entityType: "habit",
    field: "title",
    label: "습관명",
    group: "identity",
    valueType: "text",
    display: "text",
    placeholder: "예: 아침 묵상",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["title", "name", "habit", "습관", "습관명", "이름"],
  },
  {
    key: "habit.icon",
    entityType: "habit",
    field: "icon",
    label: "아이콘",
    group: "identity",
    valueType: "text",
    display: "text",
    placeholder: "•",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["icon", "emoji", "아이콘", "이모지"],
  },
  {
    key: "habit.isActive",
    entityType: "habit",
    field: "isActive",
    label: "활성 상태",
    group: "status",
    valueType: "boolean",
    display: "checkbox",
    placeholder: "활성화",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["active", "status", "enabled", "활성", "상태", "사용"],
  },
  {
    key: "habit.schedule",
    entityType: "habit",
    field: "schedule",
    label: "스케줄",
    group: "domain",
    valueType: "text",
    display: "text",
    placeholder: "daily / weekday / weekly",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["schedule", "repeat", "cadence", "스케줄", "반복", "주기"],
  },
  {
    key: "habit.description",
    entityType: "habit",
    field: "description",
    label: "설명",
    group: "review",
    valueType: "longText",
    display: "textarea",
    placeholder: "습관을 유지하는 기준이나 의도를 적어둡니다.",
    defaultVisibleInDetail: true,
    sourceAliases: ["description", "note", "memo", "설명", "메모", "비고"],
  },
];
