import type { PropertyDefinition, PropertyGroupDefinition, PropertyOption } from "./types";

export const MEDIA_TYPE_OPTIONS: PropertyOption[] = [
  { value: "game", label: "게임" },
  { value: "book", label: "책" },
  { value: "screen", label: "영상" },
];

export const MEDIA_STATUS_OPTIONS: PropertyOption[] = [
  { value: "backlog", label: "대기" },
  { value: "consuming", label: "보는 중" },
  { value: "completed", label: "완료" },
  { value: "dropped", label: "중단" },
];

export const MEDIA_PROPERTY_GROUPS: PropertyGroupDefinition[] = [
  { key: "identity", label: "기본 정보", defaultOpen: true },
  { key: "classification", label: "분류", defaultOpen: true },
  { key: "status", label: "상태", defaultOpen: true },
  { key: "dates", label: "날짜와 분량", defaultOpen: true },
  { key: "review", label: "감상", defaultOpen: true },
];

export const MEDIA_PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  {
    key: "media.title",
    entityType: "media",
    field: "title",
    label: "제목",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["title", "name", "제목", "이름"],
  },
  {
    key: "media.originalTitle",
    entityType: "media",
    field: "originalTitle",
    label: "원제",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["original title", "원제", "원본 제목"],
  },
  {
    key: "media.creator",
    entityType: "media",
    field: "creator",
    label: "창작자",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["creator", "director", "developer", "창작자", "감독", "개발사"],
  },
  {
    key: "media.author",
    entityType: "media",
    field: "author",
    label: "저자",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["author", "writer", "저자", "작가"],
  },
  {
    key: "media.studio",
    entityType: "media",
    field: "studio",
    label: "스튜디오",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["studio", "publisher", "production", "스튜디오", "제작사"],
  },
  {
    key: "media.mediaType",
    entityType: "media",
    field: "mediaType",
    label: "미디어 타입",
    group: "classification",
    valueType: "select",
    display: "segmented",
    options: MEDIA_TYPE_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["media type", "type", "유형", "종류", "타입"],
  },
  {
    key: "media.subtype",
    entityType: "media",
    field: "subtype",
    label: "세부 타입",
    group: "classification",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["subtype", "sub type", "세부 타입", "하위 유형"],
  },
  {
    key: "media.screenKind",
    entityType: "media",
    field: "screenKind",
    label: "영상 종류",
    group: "classification",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["screen kind", "video kind", "영상 종류"],
  },
  {
    key: "media.platformOrPublisher",
    entityType: "media",
    field: "platformOrPublisher",
    label: "플랫폼/출판사",
    group: "classification",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["platform", "publisher", "플랫폼", "출판사"],
  },
  {
    key: "media.genre",
    entityType: "media",
    field: "genre",
    label: "장르",
    group: "classification",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["genre", "장르"],
  },
  {
    key: "media.status",
    entityType: "media",
    field: "status",
    label: "상태",
    group: "status",
    valueType: "select",
    display: "segmented",
    options: MEDIA_STATUS_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["status", "상태"],
  },
  {
    key: "media.rewatchValue",
    entityType: "media",
    field: "rewatchValue",
    label: "다시 볼 가치",
    group: "status",
    valueType: "boolean",
    display: "checkbox",
    placeholder: "다시 볼 가치 있음",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["rewatch", "replay", "다시 볼 가치", "재시청"],
  },
  {
    key: "media.releaseYear",
    entityType: "media",
    field: "releaseYear",
    label: "출시연도",
    group: "dates",
    valueType: "number",
    display: "number",
    defaultVisibleInDetail: true,
    sourceAliases: ["release year", "year", "출시연도", "연도"],
  },
  {
    key: "media.loggedAt",
    entityType: "media",
    field: "loggedAt",
    label: "기록일",
    group: "dates",
    valueType: "date",
    display: "date",
    defaultVisibleInDetail: true,
    sourceAliases: ["logged at", "log date", "기록일", "날짜"],
  },
  {
    key: "media.startedAt",
    entityType: "media",
    field: "startedAt",
    label: "시작일",
    group: "dates",
    valueType: "date",
    display: "date",
    defaultVisibleInDetail: true,
    sourceAliases: ["started at", "start date", "시작일"],
  },
  {
    key: "media.completedAt",
    entityType: "media",
    field: "completedAt",
    label: "완료일",
    group: "dates",
    valueType: "date",
    display: "date",
    defaultVisibleInDetail: true,
    sourceAliases: ["completed at", "finish date", "end date", "완료일"],
  },
  {
    key: "media.playTime",
    entityType: "media",
    field: "playTime",
    label: "플레이타임/분",
    group: "dates",
    valueType: "number",
    display: "number",
    defaultVisibleInDetail: true,
    sourceAliases: ["play time", "runtime", "duration", "플레이타임", "상영 시간"],
  },
  {
    key: "media.pages",
    entityType: "media",
    field: "pages",
    label: "페이지",
    group: "dates",
    valueType: "number",
    display: "number",
    defaultVisibleInDetail: true,
    sourceAliases: ["pages", "page count", "페이지"],
  },
  {
    key: "media.rating",
    entityType: "media",
    field: "rating",
    label: "평점",
    group: "review",
    valueType: "number",
    display: "number",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["rating", "score", "평점", "점수"],
  },
  {
    key: "media.evaluation",
    entityType: "media",
    field: "evaluation",
    label: "평가",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["evaluation", "평가"],
  },
  {
    key: "media.review",
    entityType: "media",
    field: "review",
    label: "감상",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["review", "notes", "감상", "리뷰"],
  },
  {
    key: "media.content",
    entityType: "media",
    field: "content",
    label: "내용 메모",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["content", "memo", "내용", "메모"],
  },
  {
    key: "media.relationNote",
    entityType: "media",
    field: "relationNote",
    label: "관계/연결 메모",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["relation note", "connection note", "관계", "연결 메모"],
  },
];
