import type { PropertyDefinition, PropertyGroupDefinition, PropertyOption } from "./types";

export const PERSON_STATUS_OPTIONS: PropertyOption[] = [
  { value: "active", label: "활성" },
  { value: "dormant", label: "휴면" },
  { value: "observing", label: "관찰" },
];

export const PERSON_LAYER_OPTIONS: PropertyOption[] = [
  { value: "5", label: "핵심 5" },
  { value: "15", label: "친밀 15" },
  { value: "50", label: "친구 50" },
  { value: "150", label: "느슨한 150" },
];

export const PERSON_PROPERTY_GROUPS: PropertyGroupDefinition[] = [
  { key: "identity", label: "기본 정보", defaultOpen: true },
  { key: "classification", label: "관계 분류", defaultOpen: true },
  { key: "domain", label: "관계 리듬", defaultOpen: true },
  { key: "dates", label: "기념일", defaultOpen: true },
  { key: "source", label: "연락처", defaultOpen: true },
  { key: "review", label: "프로필", defaultOpen: true },
];

export const PERSON_PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  {
    key: "person.name",
    entityType: "person",
    field: "name",
    label: "이름",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["name", "title", "이름", "성명", "제목"],
  },
  {
    key: "person.nickname",
    entityType: "person",
    field: "nickname",
    label: "닉네임",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["nickname", "별명", "닉네임"],
  },
  {
    key: "person.aliases",
    entityType: "person",
    field: "aliases",
    label: "별칭",
    group: "identity",
    valueType: "multiSelect",
    display: "chip",
    placeholder: "별칭",
    defaultVisibleInDetail: true,
    sourceAliases: ["alias", "aliases", "별칭"],
  },
  {
    key: "person.groups",
    entityType: "person",
    field: "groups",
    label: "그룹",
    group: "classification",
    valueType: "multiSelect",
    display: "chip",
    placeholder: "그룹",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["group", "groups", "tag", "tags", "그룹", "태그"],
  },
  {
    key: "person.status",
    entityType: "person",
    field: "status",
    label: "관계 상태",
    group: "classification",
    valueType: "select",
    display: "segmented",
    options: PERSON_STATUS_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["status", "상태", "관계 상태"],
  },
  {
    key: "person.dunbarLayer",
    entityType: "person",
    field: "dunbarLayer",
    label: "관계 레이어",
    group: "classification",
    valueType: "select",
    display: "select",
    options: PERSON_LAYER_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["dunbar", "layer", "레이어", "관계 레이어"],
  },
  {
    key: "person.intimacy",
    entityType: "person",
    field: "intimacy",
    label: "친밀도",
    group: "domain",
    valueType: "number",
    display: "number",
    defaultVisibleInDetail: true,
    sourceAliases: ["intimacy", "closeness", "친밀도"],
  },
  {
    key: "person.contactCadenceDays",
    entityType: "person",
    field: "contactCadenceDays",
    label: "연락 주기/일",
    group: "domain",
    valueType: "number",
    display: "number",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["cadence", "contact cadence", "연락 주기"],
  },
  {
    key: "person.birthDate",
    entityType: "person",
    field: "birthDate",
    label: "생일",
    group: "dates",
    valueType: "date",
    display: "date",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["birthday", "birth date", "생일"],
  },
  {
    key: "person.birthdayMemo",
    entityType: "person",
    field: "birthdayMemo",
    label: "생일 기록",
    group: "dates",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["birthday memo", "생일 메모", "생일 기록"],
  },
  {
    key: "person.phone",
    entityType: "person",
    field: "phone",
    label: "전화",
    group: "source",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["phone", "mobile", "tel", "전화", "휴대폰"],
  },
  {
    key: "person.email",
    entityType: "person",
    field: "email",
    label: "이메일",
    group: "source",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["email", "mail", "이메일", "메일"],
  },
  {
    key: "person.address",
    entityType: "person",
    field: "address",
    label: "주소",
    group: "source",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["address", "주소"],
  },
  {
    key: "person.socialLinks",
    entityType: "person",
    field: "socialLinks",
    label: "소셜 링크",
    group: "source",
    valueType: "text",
    display: "text",
    defaultVisibleInDetail: true,
    sourceAliases: ["social", "instagram", "linkedin", "소셜", "링크"],
  },
  {
    key: "person.coreValue",
    entityType: "person",
    field: "coreValue",
    label: "핵심 가치",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["core value", "핵심 가치"],
  },
  {
    key: "person.bio",
    entityType: "person",
    field: "bio",
    label: "소개",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["bio", "description", "소개", "설명"],
  },
  {
    key: "person.profileBody",
    entityType: "person",
    field: "profileBody",
    label: "프로필 본문",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["profile body", "notes", "프로필", "메모"],
  },
];
