import type { PropertyDefinition, PropertyGroupDefinition, PropertyOption } from "./types";

export const PLACE_CATEGORY_OPTIONS: PropertyOption[] = [
  { value: "restaurant", label: "식당" },
  { value: "cafe", label: "카페" },
  { value: "shop", label: "상점/공간" },
];

export const PLACE_PROPERTY_GROUPS: PropertyGroupDefinition[] = [
  { key: "identity", label: "장소 기본", defaultOpen: true },
  { key: "classification", label: "분류", defaultOpen: true },
  { key: "source", label: "위치", defaultOpen: true },
  { key: "dates", label: "방문 정보", defaultOpen: true },
  { key: "review", label: "메모", defaultOpen: true },
];

export const PLACE_PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  {
    key: "place.name",
    entityType: "place",
    field: "name",
    label: "장소명",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["title", "name", "place", "장소", "장소명", "이름"],
  },
  {
    key: "place.category",
    entityType: "place",
    field: "category",
    label: "분류",
    group: "classification",
    valueType: "select",
    display: "segmented",
    options: PLACE_CATEGORY_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["category", "type", "kind", "분류", "유형", "종류"],
  },
  {
    key: "place.address",
    entityType: "place",
    field: "address",
    label: "주소",
    group: "source",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["address", "location", "주소", "위치"],
  },
  {
    key: "place.mapUrl",
    entityType: "place",
    field: "mapUrl",
    label: "지도 링크",
    group: "source",
    valueType: "url",
    display: "url",
    defaultVisibleInDetail: true,
    sourceAliases: ["map", "map url", "url", "지도", "지도 링크"],
  },
  {
    key: "place.firstVisitedAt",
    entityType: "place",
    field: "firstVisitedAt",
    label: "첫 방문일",
    group: "dates",
    valueType: "date",
    display: "date",
    defaultVisibleInDetail: true,
    sourceAliases: ["first visit", "first visited", "첫 방문", "첫 방문일"],
  },
  {
    key: "place.lastVisitedAt",
    entityType: "place",
    field: "lastVisitedAt",
    label: "최근 방문일",
    group: "dates",
    valueType: "date",
    display: "date",
    defaultVisibleInDetail: true,
    sourceAliases: ["last visit", "last visited", "최근 방문", "최근 방문일"],
  },
  {
    key: "place.visitCount",
    entityType: "place",
    field: "visitCount",
    label: "방문 수",
    group: "dates",
    valueType: "number",
    display: "number",
    defaultVisibleInDetail: true,
    sourceAliases: ["visit count", "visits", "방문 수", "방문횟수"],
  },
  {
    key: "place.averageRating",
    entityType: "place",
    field: "averageRating",
    label: "평균 평점",
    group: "review",
    valueType: "number",
    display: "number",
    defaultVisibleInDetail: true,
    sourceAliases: ["rating", "average rating", "score", "평점", "점수"],
  },
  {
    key: "place.review",
    entityType: "place",
    field: "review",
    label: "장소 메모",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["notes", "memo", "review", "description", "메모", "후기", "비고"],
  },
];
