import type { PropertyDefinition, PropertyGroupDefinition, PropertyOption } from "./types";

export const PROJECT_KIND_OPTIONS: PropertyOption[] = [
  { value: "project", label: "프로젝트" },
  { value: "area", label: "영역" },
];

export const PROJECT_STATUS_OPTIONS: PropertyOption[] = [
  { value: "active", label: "활성" },
  { value: "paused", label: "보류" },
  { value: "archived", label: "보관" },
];

export const PROJECT_COLOR_OPTIONS: PropertyOption[] = [
  { value: "gold", label: "골드" },
  { value: "sky", label: "스카이" },
  { value: "orange", label: "오렌지" },
  { value: "slate", label: "슬레이트" },
  { value: "green", label: "그린" },
];

export const PROJECT_PROPERTY_GROUPS: PropertyGroupDefinition[] = [
  { key: "identity", label: "기본 정보", defaultOpen: true },
  { key: "classification", label: "분류", defaultOpen: true },
  { key: "status", label: "상태", defaultOpen: true },
  { key: "dates", label: "일정", defaultOpen: true },
  { key: "review", label: "설명", defaultOpen: false },
];

export const PROJECT_PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  {
    key: "project.title",
    entityType: "project",
    field: "title",
    label: "프로젝트 이름",
    group: "identity",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["title", "name", "project", "프로젝트", "이름", "제목"],
  },
  {
    key: "project.icon",
    entityType: "project",
    field: "icon",
    label: "아이콘",
    group: "identity",
    valueType: "text",
    display: "text",
    placeholder: "🛟",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["icon", "emoji", "아이콘"],
  },
  {
    key: "project.kind",
    entityType: "project",
    field: "kind",
    label: "종류",
    group: "classification",
    valueType: "select",
    display: "segmented",
    options: PROJECT_KIND_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["kind", "type", "종류", "유형"],
  },
  {
    key: "project.category",
    entityType: "project",
    field: "category",
    label: "카테고리",
    group: "classification",
    valueType: "text",
    display: "text",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["category", "카테고리", "분류"],
  },
  {
    key: "project.color",
    entityType: "project",
    field: "color",
    label: "색상",
    group: "classification",
    valueType: "select",
    display: "select",
    options: PROJECT_COLOR_OPTIONS,
    defaultVisibleInDetail: true,
    sourceAliases: ["color", "색", "색상"],
  },
  {
    key: "project.status",
    entityType: "project",
    field: "status",
    label: "상태",
    group: "status",
    valueType: "select",
    display: "segmented",
    options: PROJECT_STATUS_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["status", "state", "상태"],
  },
  {
    key: "project.targetDate",
    entityType: "project",
    field: "targetDate",
    label: "목표일",
    group: "dates",
    valueType: "date",
    display: "date",
    allowEmpty: true,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["target date", "due", "deadline", "목표일", "마감일"],
  },
  {
    key: "project.description",
    entityType: "project",
    field: "description",
    label: "설명",
    group: "review",
    valueType: "longText",
    display: "textarea",
    defaultVisibleInDetail: true,
    sourceAliases: ["description", "memo", "notes", "설명", "메모"],
  },
];
