import { ZETTEL_DOCUMENT_KIND_OPTIONS } from "@/lib/vault/zettel-properties";

import type { PropertyDefinition, PropertyGroupDefinition, PropertyOption } from "./types";

export const ZETTEL_TYPE_OPTIONS: PropertyOption[] = [
  { value: "fleeting", label: "임시" },
  { value: "literature", label: "문헌" },
  { value: "permanent", label: "영구" },
  { value: "moc", label: "MOC" },
  { value: "reference", label: "참고" },
];

export const ZETTEL_STATUS_OPTIONS: PropertyOption[] = [
  { value: "draft", label: "초안" },
  { value: "active", label: "활성" },
  { value: "needs_review", label: "검토 필요" },
  { value: "archived", label: "보관" },
];

export const ZETTEL_SOURCE_RELIABILITY_OPTIONS: PropertyOption[] = [
  { value: "unknown", label: "미상" },
  { value: "primary", label: "1차 출처" },
  { value: "secondary", label: "2차 출처" },
  { value: "tertiary", label: "3차 출처" },
  { value: "personal", label: "개인 기록" },
  { value: "imported", label: "가져옴" },
  { value: "mixed", label: "혼합" },
];

export const ZETTEL_REVIEW_CADENCE_OPTIONS: PropertyOption[] = [
  { value: "none", label: "없음" },
  { value: "weekly", label: "매주" },
  { value: "monthly", label: "매월" },
  { value: "quarterly", label: "분기" },
  { value: "yearly", label: "매년" },
];

export const ZETTEL_PROPERTY_GROUPS: PropertyGroupDefinition[] = [
  { key: "classification", label: "분류", defaultOpen: true },
  { key: "domain", label: "회수 단서", defaultOpen: true },
  { key: "review", label: "검토", defaultOpen: true },
  { key: "source", label: "출처 정보", defaultOpen: true },
];

export const ZETTEL_PROPERTY_DEFINITIONS: PropertyDefinition[] = [
  {
    key: "zettel.type",
    entityType: "zettel",
    field: "type",
    label: "메모 타입",
    group: "classification",
    valueType: "select",
    display: "segmented",
    options: ZETTEL_TYPE_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["type", "유형", "종류"],
  },
  {
    key: "zettel.documentKind",
    entityType: "zettel",
    field: "documentKind",
    label: "문서 종류",
    group: "classification",
    valueType: "select",
    display: "select",
    options: ZETTEL_DOCUMENT_KIND_OPTIONS,
    allowEmpty: true,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["kind", "document kind", "문서 종류", "유형", "종류"],
  },
  {
    key: "zettel.status",
    entityType: "zettel",
    field: "status",
    label: "상태",
    group: "classification",
    valueType: "select",
    display: "segmented",
    options: ZETTEL_STATUS_OPTIONS,
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["status", "상태"],
  },
  {
    key: "zettel.category",
    entityType: "zettel",
    field: "category",
    label: "카테고리",
    group: "domain",
    valueType: "text",
    display: "text",
    placeholder: "신앙/종교, 창작, 문서 아카이브...",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["category", "카테고리", "분류"],
  },
  {
    key: "zettel.tags",
    entityType: "zettel",
    field: "tags",
    label: "태그",
    group: "domain",
    valueType: "multiSelect",
    display: "chip",
    placeholder: "태그",
    defaultVisibleInList: true,
    defaultVisibleInDetail: true,
    sourceAliases: ["tags", "tag", "topic", "keyword", "태그", "키워드"],
  },
  {
    key: "zettel.aliases",
    entityType: "zettel",
    field: "aliases",
    label: "별칭",
    group: "domain",
    valueType: "multiSelect",
    display: "chip",
    placeholder: "별칭",
    defaultVisibleInDetail: true,
    sourceAliases: ["alias", "aliases", "별칭"],
  },
  {
    key: "zettel.sourceReliability",
    entityType: "zettel",
    field: "sourceReliability",
    label: "출처 신뢰도",
    group: "review",
    valueType: "select",
    display: "select",
    options: ZETTEL_SOURCE_RELIABILITY_OPTIONS,
    defaultVisibleInDetail: true,
    sourceAliases: ["reliability", "source reliability", "신뢰도", "출처 신뢰도"],
  },
  {
    key: "zettel.reviewCadence",
    entityType: "zettel",
    field: "reviewCadence",
    label: "검토 주기",
    group: "review",
    valueType: "select",
    display: "select",
    options: ZETTEL_REVIEW_CADENCE_OPTIONS,
    defaultVisibleInDetail: true,
    sourceAliases: ["review cadence", "복습 주기", "검토 주기"],
  },
  {
    key: "zettel.reviewDueAt",
    entityType: "zettel",
    field: "reviewDueAt",
    label: "다음 검토일",
    group: "review",
    valueType: "date",
    display: "date",
    defaultVisibleInDetail: true,
    sourceAliases: ["review due", "복습일", "검토일", "다음 검토일"],
  },
  {
    key: "zettel.source",
    entityType: "zettel",
    field: "source",
    label: "출처",
    group: "source",
    valueType: "text",
    display: "text",
    placeholder: "Notion, 설교 노트, 개인 기록...",
    defaultVisibleInDetail: true,
    sourceAliases: ["source", "출처"],
  },
  {
    key: "zettel.sourceUrl",
    entityType: "zettel",
    field: "sourceUrl",
    label: "출처 URL",
    group: "source",
    valueType: "url",
    display: "url",
    placeholder: "https://...",
    defaultVisibleInDetail: true,
    sourceAliases: ["source url", "url", "link", "링크", "출처 URL"],
  },
  {
    key: "zettel.originalCreatedAt",
    entityType: "zettel",
    field: "originalCreatedAt",
    label: "원본 생성일",
    group: "source",
    valueType: "date",
    display: "date",
    defaultVisibleInDetail: true,
    sourceAliases: ["created", "created time", "date", "날짜", "생성 일시", "생성일", "원본 생성일"],
  },
];
